#index:
#    path: /
#    controller: App\Controller\DefaultController::index

jobs_nearby:
    path: /job/api/nearby
    controller: App\Controller\JobController:find_nearby

login:
    path: /logowanie
    controller: App\Controller\UserController:login

